# Project: Project0912-2
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main0912-2.o
LINKOBJ  = main0912-2.o
LIBS     = -L"D:/ruanjian/Dev-Cpp/MinGW64/lib" -L"D:/ruanjian/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/ruanjian/Dev-Cpp/MinGW64/include" -I"D:/ruanjian/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/ruanjian/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/ruanjian/Dev-Cpp/MinGW64/include" -I"D:/ruanjian/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/ruanjian/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/ruanjian/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project0912-2.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main0912-2.o: main0912-2.cpp
	$(CPP) -c main0912-2.cpp -o main0912-2.o $(CXXFLAGS)
