# Project: Project0524-3
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main0524-3.o
LINKOBJ  = main0524-3.o
LIBS     = -L"D:/ruanjian/Dev-Cpp/MinGW64/lib" -L"D:/ruanjian/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/ruanjian/Dev-Cpp/MinGW64/include" -I"D:/ruanjian/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/ruanjian/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/ruanjian/Dev-Cpp/MinGW64/include" -I"D:/ruanjian/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/ruanjian/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/ruanjian/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project0524-3.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main0524-3.o: main0524-3.cpp
	$(CPP) -c main0524-3.cpp -o main0524-3.o $(CXXFLAGS)
